mod-name: CommunityTechTree
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - CommunityTechTree
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
    - ForModders.md
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 534  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 241908  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
